name: deploy to playstore
on:
  push:
    branches:
      - main

env:
  VITE_TRACCAR_SERVER: ${{ vars.VITE_TRACCAR_SERVER }}
  APP_ID: ${{ vars.APP_ID }}
  APP_NAME: ${{ vars.APP_NAME }}
  APP_IDENTIFIER: ${{ vars.APP_IDENTIFIER }}

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: npm run build-android
      - run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > /home/runner/keystore
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_PLAY_STORE }}" | base64 --decode > google-secret.json
          echo '${{ secrets.GOOGLE_CLOUD_AUTH }}' > gc_keys.json
          bundle exec fastlane android beta
        working-directory: traccar-web/android
